import 'package:flutter/material.dart';
import 'lms_models.dart';
import 'premium_screen.dart';
import 'premium_service.dart';

class LearningPage extends StatefulWidget {
  final PremiumService premium;
  const LearningPage({super.key, required this.premium});
  @override State<LearningPage> createState() => _LearningPageState();
}
class _LearningPageState extends State<LearningPage> {
  late final LmsStore store;
  String? category;
  @override void initState() { super.initState(); store = LmsStore(access: LearningAccess.free); store.loadCourses(); }
  @override void dispose() { store.dispose(); super.dispose(); }
  @override Widget build(BuildContext context) => AnimatedBuilder(animation: store, builder: (_, __) => Scaffold(appBar: AppBar(title: const Text('Learn'), actions: [IconButton(onPressed: () => _showGenerator(context), icon: const Icon(Icons.auto_awesome))]), body: Column(children: [SizedBox(height: 56, child: ListView(scrollDirection: Axis.horizontal, padding: const EdgeInsets.all(8), children: [FilterChip(label: const Text('All'), selected: category == null, onSelected: (_) { setState(() => category = null); store.loadCourses(); }), ...lmsCategories.map((c) => Padding(padding: const EdgeInsets.only(left: 8), child: FilterChip(label: Text(c.name), selected: category == c.id, onSelected: (_) { setState(() => category = c.id); store.loadCourses(category: c.id); })))])), Expanded(child: _body(context))]));
  Widget _body(BuildContext context) { if (store.loading) return const Center(child: CircularProgressIndicator()); if (store.error != null) return Center(child: Text(store.error!)); if (store.courses.isEmpty) return const _EmptyLibrary(); return ListView.builder(itemCount: store.courses.length, itemBuilder: (_, i) => _CourseTile(course: store.courses[i], canOpen: store.canOpen(store.courses[i]), onTap: () { if (!store.canOpen(store.courses[i])) { Navigator.push(context, MaterialPageRoute(builder: (_) => PremiumScreen(service: widget.premium))); } })); }
  void _showGenerator(BuildContext context) => showModalBottomSheet(context: context, isScrollControlled: true, builder: (_) => const CourseGeneratorSheet());
}
class _EmptyLibrary extends StatelessWidget { const _EmptyLibrary(); @override Widget build(BuildContext context) => const Center(child: Padding(padding: EdgeInsets.all(28), child: Column(mainAxisSize: MainAxisSize.min, children: [Icon(Icons.menu_book, size: 56), SizedBox(height: 12), Text('No published courses yet', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)), Text('Courses are loaded from the learning service. Add and publish content from the admin dashboard without updating the app.')]))); }
class _CourseTile extends StatelessWidget { final LmsCourse course; final bool canOpen; final VoidCallback onTap; const _CourseTile({required this.course, required this.canOpen, required this.onTap}); @override Widget build(BuildContext context) => Card(child: ListTile(onTap: onTap, leading: CircleAvatar(child: Icon(course.premium ? Icons.workspace_premium : Icons.menu_book)), title: Text(course.title), subtitle: Text('${course.category} · ${course.level} · ${course.durationMinutes} min\n${course.shortDescription}'), isThreeLine: true, trailing: canOpen ? const Icon(Icons.chevron_right) : const Icon(Icons.lock))); }
class CourseGeneratorSheet extends StatefulWidget { const CourseGeneratorSheet({super.key}); @override State<CourseGeneratorSheet> createState() => _CourseGeneratorSheetState(); }
class _CourseGeneratorSheetState extends State<CourseGeneratorSheet> { final topic = TextEditingController(); final objectives = TextEditingController(); String category = lmsCategories.first.id; String level = 'beginner'; int modules = 4; @override Widget build(BuildContext context) => Padding(padding: EdgeInsets.only(left: 20, right: 20, top: 20, bottom: MediaQuery.of(context).viewInsets.bottom + 20), child: ListView(shrinkWrap: true, children: [Text('AI Course Generator', style: Theme.of(context).textTheme.headlineSmall), const Text('Admin-only. The server checks for similar courses, validates the generated schema, and saves drafts for review.'), const SizedBox(height: 12), TextField(controller: topic, decoration: const InputDecoration(labelText: 'Course topic')), DropdownButtonFormField(value: category, items: lmsCategories.map((c) => DropdownMenuItem(value: c.id, child: Text(c.name))).toList(), onChanged: (v) => setState(() => category = v!)), DropdownButtonFormField(value: level, items: ['beginner', 'intermediate', 'advanced'].map((v) => DropdownMenuItem(value: v, child: Text(v))).toList(), onChanged: (v) => setState(() => level = v!)), TextField(controller: objectives, decoration: const InputDecoration(labelText: 'Learning objectives')), Slider(value: modules.toDouble(), min: 1, max: 20, divisions: 19, label: '$modules modules', onChanged: (v) => setState(() => modules = v.round())), FilledButton.icon(onPressed: topic.text.trim().isEmpty ? null : () => Navigator.pop(context), icon: const Icon(Icons.auto_awesome), label: const Text('Generate draft for review'))])); }
}
